name: Java Code Format

on:
  pull_request:
    branches: [ testing ]
    types: [opened, synchronize]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  format-code:
    runs-on: ubuntu-latest
    # Don't run on PRs from forks
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
        
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Format code with Google Java Format
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace --skip-sorting-imports"
          skipCommit: true
          
      - name: Run Checkstyle to ensure compatibility
        run: mvn checkstyle:check -Dcheckstyle.skip=false
        continue-on-error: true
      
      - name: Check for modified files
        id: git-check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "modified=true" >> $GITHUB_OUTPUT
          else
            echo "modified=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request with formatted code
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'style: Format code according to project style'
          branch: format-code-${{ github.head_ref || github.ref_name }}
          delete-branch: true
          title: 'Format code for ${{ github.head_ref || github.ref_name }}'
          body: |
            This PR contains automatically formatted code based on project style guidelines.
            
            Changes made by the automatic code formatter. Please review the changes carefully before merging.
            
            - Formatted Java files according to Google Java Format
            - Style conforms to project checkstyle rules
          labels: automated-pr, code-formatting
          base: ${{ github.head_ref || github.ref_name }}
          draft: false
