name: Java Linter

on:
  pull_request:
    branches: [ testing, main, acceptance, dev ]
    types: [opened, synchronize]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  lint-code:
    runs-on: ubuntu-latest
    # Don't run on PRs from forks
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Format code with Google Java Format
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "style: Apply Google Java Format"
          version: "1.15.0"
          
      - name: Run Checkstyle
        run: mvn checkstyle:check
        continue-on-error: true
      
      - name: Generate Checkstyle Report
        if: success() || failure()
        run: mvn site -DgenerateReports=false
        
      - name: Publish Checkstyle Report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/site/checkstyle.html
