name: Java Linter

on:
  pull_request:
    branches: [ testing, main, acceptance, dev ]
    types: [opened, synchronize]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  lint-code:
    runs-on: ubuntu-latest
    # Don't run on PRs from forks
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Add Spotless plugin to pom.xml
        run: |
          # Check if the spotless plugin is already in the pom.xml
          if ! grep -q "com.diffplug.spotless" "pom.xml"; then
            # Use sed to add the Spotless plugin before the closing plugins tag
            sed -i '/<\/plugins>/i \
            <plugin>\
                <groupId>com.diffplug.spotless</groupId>\
                <artifactId>spotless-maven-plugin</artifactId>\
                <version>2.22.8</version>\
                <configuration>\
                    <java>\
                        <googleJavaFormat>\
                            <version>1.15.0</version>\
                            <style>GOOGLE</style>\
                        </googleJavaFormat>\
                        <removeUnusedImports/>\
                    </java>\
                </configuration>\
            </plugin>' pom.xml
          fi
      
      - name: Format code with Spotless
        run: mvn spotless:apply
      
      - name: Run Checkstyle
        run: mvn checkstyle:check
        continue-on-error: true
      
      - name: Check for modified files
        id: git-check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "modified=true" >> $GITHUB_OUTPUT
          else
            echo "modified=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Suggest code formatting changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          echo "### Code formatting suggestions" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The linter has detected code style issues. Here's a summary of changes that should be made:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "```diff" >> $GITHUB_STEP_SUMMARY
          git diff --unified=1 >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "To apply these changes locally, run: `mvn spotless:apply`" >> $GITHUB_STEP_SUMMARY
          
          # Also output to the workflow log
          echo "Code formatting issues detected. Please run 'mvn spotless:apply' locally to fix them."
          git diff --unified=1
      
      - name: Generate Checkstyle Report
        if: success() || failure()
        run: mvn site -DgenerateReports=false
        
      - name: Publish Checkstyle Report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/site/checkstyle.html
